user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar_size: 80
  thumb_size: 50
  per_page: 10
category:
  name:
    max_length: 255
  per_page: 8
comment:
  page_comment: 10
  content:
    max_length: 500
comic:
  name:
    max_length: 100
  author:
    max_length: 100
  description:
    max_length: 2000
  thumb_size: 10
  thumb:
    width: 720
    height: 960
  per_page: 10
  slide_per_page: 10
  popular_per_page: 12
  latest_update_per_page: 8
  recommended_per_page: 8
  finised_per_page: 16
  trendding_right: 5
  created: 0
  updated: 1
  hot: 2
  finished: 3
chapter:
  name:
    max_length: 100
  per_page: 10
  for_user_per_page: 25
  per_page_default: 10
factories:
  comic:
    description: 100
  comment:
    content: 500
follow: "Follow"
like: "Like"
